# Generated by Django 4.1.1 on 2022-09-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultureallapi', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
