# Generated by Django 4.1.1 on 2022-09-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultureallapi', '0004_contactrequest_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
