# Generated by Django 4.1.1 on 2022-09-14 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cultureallapi', '0005_alter_consultationrequest_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='complete',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cultureallapi.questiontype'),
        ),
    ]
