# Generated by Django 4.1.1 on 2022-09-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultureallapi', '0006_contactrequest_complete_alter_question_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactrequest',
            old_name='complete',
            new_name='completed',
        ),
    ]
