# Generated by Django 4.1.2 on 2022-10-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultureallapi', '0008_consultationrequest_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
